spring:
  application:
    name: pgsqlDemo
  profiles:
    active: stg

  ### postgresql config ###
  datasource:
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.25.159:9999/test

server:
  port: 8091

# Eureka Server 地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8090/eureka/
  # eureka实例ID
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}

demo:
  gn: 22