spring:
  application:
    name: freemarker-demo
#freemarker的配置begin
  freemarker:
    suffix: .ftl
    charset: utf-8
    content-type: text/html; charset=utf-8
    template-loader-path: classpath:/templates
  mvc:
    static-path-pattern: /static/**
#freemarker的配置end

server:
  port: 8088
# Eureka Server 地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8090/eureka/
  # eureka实例ID
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
