spring:
  application:
    name: freemarker-demo
  datasource:
    url: jdbc:postgresql://120.25.167.218:5432/postgres
    username: postgres
    password: postgres

#freemarker的配置 start
  freemarker:
    suffix: .ftl
    charset: utf-8
    content-type: text/html; charset=utf-8
    template-loader-path: classpath:/templates
  mvc:
    static-path-pattern: /static/**
#freemarker的配置 end

mybatis-plus:
  configuration:
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: REUSE
    use-actual-param-name: true


server:
  port: 8088
# Eureka Server 地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8090/eureka/
  # eureka实例ID
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}