server:
  port: 8089
# Eureka Server 地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8090/eureka/
  # eureka实例ID
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
spring:
  application:
    name: common
demo:
  gn:
    ceShi : 11