server:
  port: 8089

# Eureka Server 地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8090/eureka/
  # eureka实例ID
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
spring:
  application:
    name: common

# REDIS (RedisProperties)
# Redis数据库索引（默认为0）
  redis:
    database: 0
# Redis服务器地址
    host: localhost
# Redis服务器连接端口
    port: 6379
# 连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        max-active: 100
# 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
# 连接池中的最大空闲连接
        max-idle: 20
# 连接池中的最小空闲连接
        min-idle: 1
# 连接超时时间（毫秒）
    timeout: 5000
    password: 123456
  profiles:
    active: dev

demo:
  gn:
    ceShi : 11
    list : aaa,bbb,ccc
    map : '{"aaa":"90","bbb":"80"}'
    userDto : '{"username":"gn","password":"gn","checkCode":"1234","inputCode":"1234"}'